In [55]:
# !pip install streamlit
# !pip install folium
# !pip install geopandas
import streamlit as st
import pandas as pd
import numpy as np
import folium
import streamlit.components.v1 as components
import json
import geopandas as gpd
from branca.element import Template, MacroElement
from template import template

# !pip install ipykernel>=5.1.2
# !pip install pydeck

from branca.element import Template, MacroElement

#!streamlit run /usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py

from branca.element import Template, MacroElement
from template import template
import branca.colormap as cm
st.header("Antyodaya Dashboard Rajasthan")

# Base Map##put centre of centriod of rajesthan
m = folium.Map(location=[26.5844, 73.8496],zoom_start=6, tiles='cartodbpositron')

# Reading state Data
df = pd.read_csv("Raj_dt_ma.csv")
geoData = open('Raj_dt_ma.geojson')

# Reading ac data
geo_ac_data = gpd.read_file("Raj_AC_ma.geojson")
districts = list(geo_ac_data['District'].unique())
districts.insert(0, "All")
ac_df = pd.read_csv('Raj_AC_ma.csv')

# Reading gc data
geo_gc_data = gpd.read_file("Raj_GP_ma.geojson")


# Creating dropdowns
category = st.sidebar.selectbox("Select a Category", list(df.columns[2:]))
district = st.sidebar.selectbox("Select a District", districts)

# Function to calculate opacity
def calculate_opacity(df, category, i):
    colors = ['#F1EEF6', '#D4B9DA', '#C994C7',
                        '#DF65B0', '#E7298A', '#CE1256', '#91003F']
    temp = list(df[category])
    try:
        op = (temp[i] - min(temp)) / (max(temp) - min(temp))
        if op <= 1 and op > 0.75:
            return colors[1]
        elif op <= 0.75 and op > 0.5:
            return colors[2]
        elif op <= 0.5 and op > 0.25:
            return  colors[4]
        else:
            return colors[6]
        # if op <= 1 and op > 0.833:
        #     return colors[6]
        # elif op <= 0.833 and op > 0.666:
        #     return colors[5]
        # elif op <= 0.666 and op > 0.499:
        #     return  colors[4]
        # elif op <= 0.499 and op > 0.332:
        #     return colors[3]
        # elif op <= 0.332 and op > 0.165:
        #     return  colors[2]
        # else:
        #     return colors[1]

    except:
        return colors[1]

if district == "All":

    choropleth = folium.Choropleth(
        geo_data=json.load(geoData),
        name='choropleth',
        data=df,
        columns=['District Name', str(category)],
        key_on='properties.District Name',
        fill_color='YlGnBu',
        fill_opacity=0.9,
        line_opacity=1,
        legend_name=str(category)
    ).add_to(m)

    # folium.LayerControl().add_to(m)
    choropleth.geojson.add_child(
    folium.features.GeoJsonTooltip(
                fields=['District Name', str(category)],
                aliases=['District Name:', str(category)+":"],
                style=("background-color: white; color: #333333; font-family: arial; font-size: 12px; padding: 10px;")))

    m.save('map2.html')
    HtmlFile = open("map2.html", 'r', encoding='utf-8')
    source_code = HtmlFile.read()
    HtmlFile.close()

    # Showing map in streamlit
    components.html(source_code,width=700, height=500)

else:
    new_geo_gc_data = geo_gc_data[geo_gc_data['District'] == str(district)]

In [56]:
geo_gc_data

,dtname,stname,OBJECTID_1,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,sdtname,...,Health & Sanitation (0-11),Women & Child Development (0-7),Social Forestry (0-1),Family Welfare (0-1),Poverty Alleviation Programme (0-6),"Khadi, Village & Cottage Industries (0-3)",Social Forestry (0-1).1,Small Scale Industries (0-1),Adult & Non-Formal Education (0-1),geometry
0,Hanumangarh,RAJASTHAN,203985.0,532321.0,15 Spm,8.0,100.0,469.0,64810.0,Pilibanga,...,2.26,2.58,0.00,0.00,0.52,0.0,0.00,0.0,0.0,POINT (74.01970 29.71308)
1,Ganganagar,RAJASTHAN,206531.0,537655.0,9 Z,8.0,99.0,458.0,64463.0,Ganganagar,...,3.00,2.00,0.00,1.00,2.00,0.0,0.00,0.0,0.0,POINT (73.81666 29.93309)
2,Ganganagar,RAJASTHAN,206336.0,537296.0,4 Bnw (banwala),8.0,99.0,459.0,64651.0,Sadulshahar,...,1.50,3.00,0.00,1.00,0.00,0.0,0.00,0.0,0.0,POINT (74.02875 29.92571)
3,Hanumangarh,RAJASTHAN,201176.0,525955.0,2 Ksp,8.0,100.0,467.0,67440.0,Tibi,...,2.50,0.50,0.00,0.00,0.00,0.0,0.00,0.0,0.0,POINT (74.47722 29.50130)
4,None,None,NaN,NaN,None,NaN,NaN,NaN,NaN,None,...,1.83,1.18,0.00,0.00,0.00,0.0,0.00,0.0,0.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3288,Pratapgarh,RAJASTHAN,108357.0,261211.0,Veerpur,8.0,131.0,697.0,108196.0,Peepalkhoont,...,3.32,2.53,0.75,0.61,0.11,0.0,0.75,0.0,0.0,POINT (74.69086 23.92058)
3289,Barmer,RAJASTHAN,134280.0,364713.0,Meghwalon Ka Tala,8.0,115.0,581.0,87654.0,Gudha Malani,...,0.50,0.50,0.00,0.00,0.00,0.0,0.00,0.0,0.0,POINT (71.39658 25.36063)
3290,Jhunjhunun,RAJASTHAN,185217.0,493350.0,Tyonda,8.0,103.0,490.0,71526.0,Khetri,...,6.00,1.00,0.17,0.17,1.00,0.0,0.17,0.0,1.0,POINT (75.88142 27.97014)
3291,Alwar,RAJASTHAN,175399.0,472827.0,Toda,8.0,104.0,503.0,73594.0,Lachhmangarh,...,7.00,2.00,1.00,1.00,0.00,0.0,1.00,1.0,0.0,POINT (76.90688 27.34581)
3292,None,None,NaN,NaN,None,NaN,NaN,NaN,NaN,None,...,4.14,2.05,0.00,0.00,0.00,0.0,0.00,0.0,0.0,None

In [57]:
new_geo_gc_data = geo_gc_data[geo_gc_data['District'] == str(district)]

In [50]:
geo_gc_data.columns

Index(['dtname', 'stname', 'OBJECTID_1', 'objectid', 'vilnam_soi', 'stcode11',
       'dtcode11', 'sdtcode11', 'vilcode11', 'sdtname', 'vilname', 'vilcode',
       'gp_code', 'gp_name', 'ishqtr', 'LOC_STAT_1', 'LOC_NAME', 'District',
       'District Code', 'Sub District', 'Sub District Code',
       'Development Block', 'Block Code', 'Parliament Constituency',
       'Assembly Constituency', 'AC Code', 'GP Code', 'Total Population',
       'Gram Panchayat', 'Agriculture (0-7)',
       'Land Improvement & Minor Irrigation (0-9)', 'Animal Husbandry (0-6)',
       'Fisheries (0-2)', 'Rural Housing (0-4)', 'Drinking Water (0-3)',
       'Roads (0-8)', 'Rural Electrification (0-3)',
       'Non-Conventional Energy (0-1)',
       'Maintenance of Community Assets (0-1)', 'Fuel & Fodder (0-1)',
       'Libraries (0-1)', 'Cultural Activities (0-1)',
       'Financial & Communication Infrastructure (0-9)',
       'Public Distribution System (0-2)', 'Education (0-6)',
       'Vocational Education (0-2)', 'Markets & Fairs (0-3)',
       'Health & Sanitation (0-11)', 'Women & Child Development (0-7)',
       'Social Forestry (0-1)', 'Family Welfare (0-1)',
       'Poverty Alleviation Programme (0-6)',
       'Khadi, Village & Cottage Industries (0-3)', 'Social Forestry (0-1).1',
       'Small Scale Industries (0-1)', 'Adult & Non-Formal Education (0-1)',
       'geometry'],
      dtype='object')

In [59]:

# len(geo_gc_data['District'].unique())
geo_gc_data['District'].unique()

array(['GANGANAGAR', 'HANUMANGARH', 'BIKANER', 'JAIPUR', 'BHILWARA',
       'UDAIPUR', 'DUNGARPUR', 'KOTA', 'JODHPUR', 'CHURU', 'SIKAR',
       'PRATAPGARH', 'NAGAUR', 'JAISALMER', 'RAJSAMAND', 'JHUNJHUNU',
       'SAWAI MADHOPUR', 'JALORE', 'ALWAR', 'BUNDI', 'SIROHI',
       'BHARATPUR', 'AJMER', 'BARAN', 'KARAULI', 'CHITTORGARH',
       'JHALAWAR', 'DHOLPUR', 'DAUSA', 'PALI', 'BARMER', 'TONK',
       'BANSWARA'], dtype=object)

In [58]:
new_geo_gc_data

Empty GeoDataFrame
Columns: [dtname, stname, OBJECTID_1, objectid, vilnam_soi, stcode11, dtcode11, sdtcode11, vilcode11, sdtname, vilname, vilcode, gp_code, gp_name, ishqtr, LOC_STAT_1, LOC_NAME, District, District Code, Sub District, Sub District Code, Development Block, Block Code, Parliament Constituency, Assembly Constituency, AC Code, GP Code, Total Population, Gram Panchayat, Agriculture (0-7), Land Improvement & Minor Irrigation (0-9), Animal Husbandry (0-6), Fisheries (0-2), Rural Housing (0-4), Drinking Water (0-3), Roads (0-8), Rural Electrification (0-3), Non-Conventional Energy (0-1), Maintenance of Community Assets (0-1), Fuel & Fodder (0-1), Libraries (0-1), Cultural Activities (0-1), Financial & Communication Infrastructure (0-9), Public Distribution System (0-2), Education (0-6), Vocational Education (0-2), Markets & Fairs (0-3), Health & Sanitation (0-11), Women & Child Development (0-7), Social Forestry (0-1), Family Welfare (0-1), Poverty Alleviation Programme (0-6), Khadi, Village & Cottage Industries (0-3), Social Forestry (0-1).1, Small Scale Industries (0-1), Adult & Non-Formal Education (0-1), geometry]
Index: []

[0 rows x 57 columns]

In [24]:
ac_df = ac_df[ac_df['District'] == district]

In [25]:
ac_df

Empty DataFrame
Columns: [District, Assembly Constituency, AC Code, Total Population, Agriculture (0-7), Land Improvement & Minor Irrigation (0-9), Animal Husbandry (0-6), Fisheries (0-2), Rural Housing (0-4), Drinking Water (0-3), Roads (0-8), Rural Electrification (0-3), Non-Conventional Energy (0-1), Maintenance of Community Assets (0-1), Fuel & Fodder (0-1), Libraries (0-1), Cultural Activities (0-1), Financial & Communication Infrastructure (0-9), Public Distribution System (0-2), Education (0-6), Vocational Education (0-2), Markets & Fairs (0-3), Health & Sanitation (0-11), Women & Child Development (0-7), Social Forestry (0-1), Family Welfare (0-1), Poverty Alleviation Programme (0-6), Khadi, Village & Cottage Industries (0-3), Social Forestry (0-1).1, Small Scale Industries (0-1), Adult & Non-Formal Education (0-1)]
Index: []

[0 rows x 31 columns]

In [26]:
dist_data = geo_ac_data[geo_ac_data['District'] == district]

In [27]:
dist_data

Empty GeoDataFrame
Columns: [ST_CODE, ST_NAME, DT_CODE, DIST_NAME, AC_NO, AC_NAME, PC_NO, PC_NAME, District, Assembly Constituency, AC Code, Total Population, Agriculture (0-7), Land Improvement & Minor Irrigation (0-9), Animal Husbandry (0-6), Fisheries (0-2), Rural Housing (0-4), Drinking Water (0-3), Roads (0-8), Rural Electrification (0-3), Non-Conventional Energy (0-1), Maintenance of Community Assets (0-1), Fuel & Fodder (0-1), Libraries (0-1), Cultural Activities (0-1), Financial & Communication Infrastructure (0-9), Public Distribution System (0-2), Education (0-6), Vocational Education (0-2), Markets & Fairs (0-3), Health & Sanitation (0-11), Women & Child Development (0-7), Social Forestry (0-1), Family Welfare (0-1), Poverty Alleviation Programme (0-6), Khadi, Village & Cottage Industries (0-3), Social Forestry (0-1).1, Small Scale Industries (0-1), Adult & Non-Formal Education (0-1), geometry]
Index: []

[0 rows x 40 columns]

In [43]:
len(geo_ac_data['District'].unique())

34

In [41]:
districts = list(geo_ac_data['District'].unique())
districts.remove(None)

In [42]:
districts

['GANGANAGAR',
 'HANUMANGARH',
 'BIKANER',
 'CHURU',
 'JHUNJHUNU',
 'JAISALMER',
 'SIKAR',
 'ALWAR',
 'JAIPUR',
 'JODHPUR',
 'BHARATPUR',
 'NAGAUR',
 'DAUSA',
 'AJMER',
 'KARAULI',
 'DHAULPUR',
 'BARMER',
 'SAWAI MADHOPUR',
 'TONK',
 'PALI',
 'BHILWARA',
 'JALOR',
 'RAJSAMAND',
 'BUNDI',
 'KOTA',
 'SIROHI',
 'BARAN',
 'CHITTAURGARH',
 'UDAIPUR',
 'JHALAWAR',
 'PRATAPGARH',
 'DUNGARPUR',
 'BANSWARA']

In [48]:
assembly_constituencies = list(geo_gc_data['Assembly Constituency'].unique())

In [49]:
len(assembly_constituencies)

190